services:
  - type: web
    name: rocky-tapswap
    env: php
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 index.php"
    envVars:
      - key: PORT
        value: 10000
